## __1. 파이토치 텐서 선언하기(PyTorch Tensor Allocation)__

In [1]:
import torch

In [2]:
''' 
1D Tensor (like vector)
'''
t = torch.FloatTensor([0., 1., 2., 3.])
print(t)

tensor([0., 1., 2., 3.])


In [3]:
print(t.dim()) # rank, 차원
print(t.shape)
print(t.size()) # .shape 와 .size()는 동일하다

1
torch.Size([4])
torch.Size([4])


In [5]:
'''
Numpy 처럼 인덱스 접근과 슬라이싱 가능하다.
'''
print(t[1], t[3]) # 인덱스 접근
print(t[1:4]) # 슬라이싱 

tensor(1.) tensor(3.)
tensor([1., 2., 3.])


In [6]:
'''
2D Tensor (like matrix)
'''
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [7]:
print(t.dim())  # rank, 차원
print(t.shape)
print(t.size()) # .shape 과 .size()는 동일

2
torch.Size([4, 3])
torch.Size([4, 3])


In [8]:
'''
Numpy 처럼 인덱스 접근과 슬라이싱 가능하다.
'''
print(t[1][2], t[3][1]) # 인덱스 접근  (6., 11.)
print(t[1:3][:]) # 슬라이싱 ([4., 5., 6.],[7., 8., 9.])

tensor(6.) tensor(11.)
tensor([[4., 5., 6.],
        [7., 8., 9.]])


In [9]:
'''
3D Tensor 도 동일하다. 넘어가자~
'''

'\n3D Tensor 도 동일하다. 넘어가자~\n'

## __2. 브로드캐스팅(Broadcasting)__

In [10]:
'''
크기가 다른 Tensor에 대해서 자동으로 크기를 맞춰서 연산을 수행하는 기능을 Broadcasing이라고 한다.
크기가 1인 차원이 있는 경우에만 적용된다. 크기가 1인 차원을 연산 가능한 크기로 변경하여 연산을 한다.
'''

'\n크기가 다른 Tensor에 대해서 자동으로 크기를 맞춰서 연산을 수행하는 기능을 Broadcasing이라고 한다.\n'

In [13]:
# vector + matrix
m1 = torch.FloatTensor([[1, 2]])   # shape : 2, 
m2 = torch.FloatTensor([[3., 4.],[5., 6.]]) # shape : 2×2
'''
m1 : [1,2]         shape : 2,
  -> [ [1, 2]
       [1, 2] ]    shape : 2×2 로 변경된다.
'''
print(m1 + m2)

tensor([[4., 6.],
        [6., 8.]])


In [16]:
'''
크기가 1인 차원을 갖지 않는 Tensor의 경우애는 Broadcasting 연산이 적용안됨
'''
m1 = torch.FloatTensor([[1, 2],[3., 4.]])   # shape : 2×2 
m2 = torch.FloatTensor([[3., 4., 5.],[6., 7., 8.]]) # shape : 2×3
#print(m1 + m2) # Error 발생한다.

## 3. __행렬곱(.matmul)과 원소곱(.mul)__

In [ ]:
'''
행렬곱 (.matmul) : 일반적으로 배운 행렬의 곱셈 방법
원소곱 (.mul) : element-wise 곱셈, 동일한 위치의 원소끼리 곱한다.
'''

In [17]:
m1 = torch.FloatTensor([[1, 2], [3, 4]]) # shape : 2×2 
m2 = torch.FloatTensor([[1], [2]])       # shape : 2×1
print(m1.matmul(m2)) # 행렬곱이 성립하는 조건이므로 이상없이 연산한다.

tensor([[ 5.],
        [11.]])


In [20]:
print(m2.matmul(m1)) 
# 행렬곱이 성립하지 않는 조건이므로 Broadcasting 후 행렬곱 연산을 할까?
# -> 행렬곱의 경우는 Broadcasting 적용안된다.

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1 and 2x2)

In [18]:
print(m1.mul(m2)) # 두 Tensor의 크기가 다르므로 Broadcasting 후 원소곱을 한다.
'''
m2 : [ [1],[2] ]       shape : 2×1
 ->  [ [1, 1],
       [2, 2]  ]       shape : 2×2
       
m1.mul(m2) :  
[  [1, 2],    [ [1, 1],      =>       [ [1, 2],
   [3, 4] ]     [2, 2] ]                [6, 8] ]
'''

tensor([[1., 2.],
        [6., 8.]])


'\nm2 : [ [1],[2] ]       shape : 2×1\n ->  [ [1, 1],\n       [2, 2]  ]       shape : 2×2\n       \nm1.mul(m2) :  \n[  [1, 2],    [ [1, 1],      =>       [ [1, 2],\n   [3, 4] ]     [2, 2] ]                [6, 8] ]\n'

## __4. 평균(mean), 합(sum)__

In [21]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean()) #.mean()은 전체 원소에 대한 평균을 반환한다.

tensor(2.5000)


In [25]:
print(t.mean(dim=0))
print(t.mean(dim=0).shape)

tensor([2., 3.])
torch.Size([2])


In [26]:
'''
dim=0 : 1번째 차원(행)
행에서의 평균을 계산하고, dim=0 차원을 제거한다.

2번째 차원(열)만 남는다.
'''

'\ndim=0 : 1번째 차원(행)\n행에서의 평균을 계산하고, dim=0 차원을 제거한다.\n\n2번째 차원(열)만 남는다.\n'

In [28]:
print(t.mean(dim=1)) # dim=1, 2번째 차원(열)의 평균을 계산하고, dim=1 차원을 제거한다.
print(t.mean(dim=1).shape) # 2×2 -> 2×1

tensor([1.5000, 3.5000])
torch.Size([2])


In [ ]:
'''
sum() 연산도 mean()연산과 동일하다.
.sum() : 모든 원소의 합.
.sum(dim=0) : dim=0인 원소들의 합을 계산하고, dim=0을 제거한다.
'''

## __5. 최대(max), 아그맥스(argmax)__

In [ ]:
'''
.max() : 원소의 최댓값을 반환한다.
.max(dim=n) : n번째 dim에서 최대값을 반환하고, n번째 dim을 제거한다.
'''

In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [30]:
print(t.max()) # Returns one value: max

tensor(4.)


In [31]:
print(t.max(dim=0)) # 1번째 dim (행)에서의 최대값을 반환한다. dim=0의 크기는 2이므로, 반환된 값은 2개이다.

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [ ]:
'''
.max(dim=n) 의 경우는 2개의 결과를 반환한다.
value : n번째 dim에서의 최댓값들.
indices : n번째 dim에서의 최댓값들의 인덱스. (argmax 라고도 한다.)

value = .max(dim=n)[0]
indices = .max(dim=n)[1]
이런식으로도 받아올 수 있다.
'''

In [32]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


---